# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ZenWu.site
subtitle: 存一些内容，记一点文字
description: 蹉跎错，消磨过，最是光阴化浮沫。
keywords: Zen.Wu
author: Zen.Wu
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.zenwu.site/
root: /
permalink: post/:abbrlink.html # :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source #资源文件夹，这个文件夹用来存放内容
public_dir: public  #公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags # 标签文件夹    
archive_dir: archives #归档文件夹
category_dir: categories #分类文件夹
code_dir: downloads/code #Include code 文件夹
i18n_dir: :lang   #国际化（i18n）文件夹
skip_render: README.md #跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。  

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: true
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 20
  order_by: -updated  ##-date  

#归档页的分页设置
archive_generator:
  per_page: 30
  yearly: true
  monthly: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
updated_option: true

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: NexT

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git #gitee
    repo: https://gitee.com/zenkin/zenkin.git
    branch: master

  - type: git #github
    repo: https://github.com/zenkinwin/zenkinwin.github.io.git
    branch: master

  - type: git #coding
    repo: https://e.coding.net/zenkin/zenkin/hexo.git
    branch: master

  - type: git #cvm
    repo: git@115.159.111.168:/home/git/zenwuhexo.git
    branch: master

  - type: baidu_url_submitter #提交百度

# search 添加百度/谷歌/本地 自定义站点内容搜索

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# 生成传统的sitemap
# 传统的sitemap
# npm install hexo-generator-sitemap --save
# 生成百度的sitemap # npm install hexo-generator-baidu-sitemap --save

sitemap:
path: sitemap.xml


baidu_url_submit:
  count: 200 #//提交最新的链接数
  host: www.zenwu.site #//在百度站长平台中注册的域名,虽然官方推荐要带有 www, 但可以不带.
  token: LRfjbTzE9VtzAx5b #//你的秘钥,每个人都不一样,获取方法在下面
  path: baidu_urls.txt #//文本文档的地址,新链接会保存在此文本文档里

# 生成全站json
# restful:
#   # site 可配置为数组选择性生成某些属性
#   # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
#   site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']        # hexo.config mix theme.config
#   posts_size: 0    # 文章列表分页，0 表示不分页
#   posts_props:      # 文章列表项的需要生成的属性
#     title: true
#     slug: true
#     date: true
#     updated: true
#     comments: false
#     path: true
#     excerpt: false
#     cover: true      # 封面图，取文章第一张图片
#     content: false
#     keywords: true
#     categories: true
#     tags: true
#   categories: true         # 分类数据
#   use_category_slug: true # Use slug for filename of category data
#   tags: true               # 标签数据
#   use_tag_slug: true      # Use slug for filename of tag data
#   post: true               # 文章数据
#   pages: true             # 额外的 Hexo 页面数据, 如 About



# recent post
mmdd_format: YYYY/MM/DD

# abbrlink config
abbrlink:
  alg: crc16  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex


#  # Security
# encrypt: # hexo-blog-encrypt
#   abstract: 有东西被加密了，请输入密码查看。
#   message: 您好，这里需要密码。
#   tags:
#   - {name: 不公开, password: zenkin}
#   template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
#   wrong_pass_message: 抱歉, 这个密码看着不太对，请再试试。
#   wrong_hash_message: 抱歉, 这个文章不能被校验，不过您还是能看看解密后的内容。
  